name: deploy to dokku

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: dokku@intergestalt.dev:2038-pre-web
        BRANCH: master
        FOLDER: ./
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        KNOWN_HOSTS_FILE: resources/known_hosts  

