name: deploy pages to dokku

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: dokku@intergestalt.monster:2038-pages
        BRANCH: master
        FOLDER: ./src/pages
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        KNOWN_HOSTS_FILE: resources/known_hosts  

